foo:
  source: data/owles.jpg
  output: data/output.jpg
  delimeter: ;
  timeout: 3
  extension_name: BinaryFileExtension
  
vector_add:
  source: data/vector.txt
  output: data/output.txt
  delimeter: ;
  extension_name: FileExtension

